version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Updated for serve port
    # depends_on:
    #   - backend
    environment:
      - REACT_APP_API_BASE=http://backend:5000/api  # Internal Docker network
    networks:
      - app-network
  db:
    image: postgres:16
    container_name: smart_url_db
    environment:
      POSTGRES_DB: alert-manager
      POSTGRES_USER: jim
      POSTGRES_PASSWORD: jim
    ports:
      - "5432:5432"  # Map host port 5432 to container port 5432


networks:
  app-network:
    driver: bridge